name: "Issue maker"

description: "Create and issue with a cat as the body"

inputs:
  issueTitle:
    description: "A name for the cat-fact issue"
    required: true
    default: "A cat fact for you"

  catFact:
    decription: "The cat fact retrieved from a previous action"
    required: true
    default: "Mona is an Octocat"

  repoToken:
    description: "Authentication token, use secrets.GITHUB_TOKEN"
    required: true
  
runs:
  using: "docker"
  image: "Dockerfile"