name: Docker Actions

on:
  pull_request:
    types: [labeled]
    # branches:
    #   - main
  
  push:
    branches:
      - main

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world
        with:
          firstGreeting: "Learning Lab User"
          secondGreeting: "Marlon Mejia"
          thirdGreeting: "Twinky"
      
      - name: meow
          uses: ./.github/actions/cat-facts