name: Docker Actions

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github(avtions/hello-world
        with:
          firstGreeting: "Learning Lab User"
          secondGreeting: "Marlon Mejia"
          thirdGreeting: "Twinky"